default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: desayunosapp_development

test:
  <<: *default
  database: desayunosapp_test

production:
  <<: *default
  database: desayunosapp_production
